name: Deploy and Run Barbers App on VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy and Run App on VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ubuntu
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            set -e
            cd /home/ubuntu
            # eski papkani o'chirib tashlaymiz
            rm -rf barbers
            # yangi kodni olib kelamiz
            git clone https://github.com/muhammadaliismoilov/barbers.git
            cd barbers
            # .env faylni yaratamiz
            echo "PORT=${{ secrets.PORT }}" > .env
            echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
            echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
            echo "DB_USER=${{ secrets.DB_USER }}" >> .env
            echo "DB_PASS=${{ secrets.DB_PASS }}" >> .env
            echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
            # dependency o'rnatamiz
            npm install
            # build qilamiz
            npm run build
            # eski processni o'chiramiz va yangisini ishga tushiramiz
            pm2 delete barbers || true
            pm2 start dist/main.js --name barbers
            pm2 save
